version: '2'
services:
    pgmaster2:
#        image: paunin/postgresql-cluster-pgsql
        build:
            context: .
            dockerfile: Postgres-latest.Dockerfile
        environment:

            NODE_ID: 1
            NODE_NAME: node1
            CLUSTER_NODE_NETWORK_NAME: pgmaster2

            POSTGRES_PASSWORD: monkey_pass
            POSTGRES_USER: monkey_user
            POSTGRES_DB: monkey_db

            CONFIGS: "listen_addresses:'*'"
        ports:
            - 5439:5432
        networks:
            cluster:
                aliases:
                    - pgmaster2
    pgpool2:
#        image: paunin/postgresql-cluster-pgpool
        build:
            context: .
            dockerfile: Pgpool-latest.Dockerfile
        depends_on:
            - pgmaster
            - pgmaster2
        environment:
            PCP_USER: pcp_user
            PCP_PASSWORD: pcp_pass

            CHECK_USER: monkey_user
            CHECK_PASSWORD: monkey_pass
            CHECK_PGCONNECT_TIMEOUT: 3 #timout for checking if primary node is healthy

            DB_USERS: monkey_user:monkey_pass # in format user:password[,user:password[...]]
            BACKENDS: "0:pgmaster::::,1:pgmaster2::::"
        ports:
            - 5431:5432
            - 9899:9898 # PCP
        networks:
            cluster:
                aliases:
                    - pgpool2